#ifndef AOI_PLCLINKDLL_GLOBAL_H
#define AOI_PLCLINKDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AOI_PLCLINKDLL_LIBRARY)
#  define AOI_PLCLINKDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AOI_PLCLINKDLLSHARED_EXPORT Q_DECL_EXPORT
#endif

#endif // AOI_PLCLINKDLL_GLOBAL_H
