#ifndef AOI_ZEBRAPRINTERDLL_GLOBAL_H
#define AOI_ZEBRAPRINTERDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AOI_ZEBRAPRINTERDLL_LIBRARY)
#  define AOI_ZEBRAPRINTERDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AOI_ZEBRAPRINTERDLLSHARED_EXPORT Q_DECL_EXPORT
#endif

#endif // AOI_ZEBRAPRINTERDLL_GLOBAL_H
